# Generated by Django 4.2.5 on 2023-10-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
